def display_board
    puts "A Tic Tac Toe Board"
    print "   "
    print "|"
    print "   "
    print "|"
    print "   "
    print "-----------"
    print "   "
    print "|"
    print "   "
    print "|"
    print "   "
    print "-----------"
    print "   "
    print "|"
    print "   "
    print "|"
    print "   "
  end